/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package youling.studio.protocol;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class GetRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6478080668065506808L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GetRequest\",\"namespace\":\"youling.studio.protocol\",\"fields\":[{\"name\":\"client_id\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GetRequest> ENCODER =
      new BinaryMessageEncoder<GetRequest>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GetRequest> DECODER =
      new BinaryMessageDecoder<GetRequest>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<GetRequest> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<GetRequest> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GetRequest>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this GetRequest to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a GetRequest from a ByteBuffer. */
  public static GetRequest fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence client_id;
  @Deprecated public java.lang.CharSequence host;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GetRequest() {}

  /**
   * All-args constructor.
   * @param client_id The new value for client_id
   * @param host The new value for host
   */
  public GetRequest(java.lang.CharSequence client_id, java.lang.CharSequence host) {
    this.client_id = client_id;
    this.host = host;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return client_id;
    case 1: return host;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: client_id = (java.lang.CharSequence)value$; break;
    case 1: host = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'client_id' field.
   * @return The value of the 'client_id' field.
   */
  public java.lang.CharSequence getClientId() {
    return client_id;
  }

  /**
   * Sets the value of the 'client_id' field.
   * @param value the value to set.
   */
  public void setClientId(java.lang.CharSequence value) {
    this.client_id = value;
  }

  /**
   * Gets the value of the 'host' field.
   * @return The value of the 'host' field.
   */
  public java.lang.CharSequence getHost() {
    return host;
  }

  /**
   * Sets the value of the 'host' field.
   * @param value the value to set.
   */
  public void setHost(java.lang.CharSequence value) {
    this.host = value;
  }

  /**
   * Creates a new GetRequest RecordBuilder.
   * @return A new GetRequest RecordBuilder
   */
  public static youling.studio.protocol.GetRequest.Builder newBuilder() {
    return new youling.studio.protocol.GetRequest.Builder();
  }

  /**
   * Creates a new GetRequest RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GetRequest RecordBuilder
   */
  public static youling.studio.protocol.GetRequest.Builder newBuilder(youling.studio.protocol.GetRequest.Builder other) {
    return new youling.studio.protocol.GetRequest.Builder(other);
  }

  /**
   * Creates a new GetRequest RecordBuilder by copying an existing GetRequest instance.
   * @param other The existing instance to copy.
   * @return A new GetRequest RecordBuilder
   */
  public static youling.studio.protocol.GetRequest.Builder newBuilder(youling.studio.protocol.GetRequest other) {
    return new youling.studio.protocol.GetRequest.Builder(other);
  }

  /**
   * RecordBuilder for GetRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GetRequest>
    implements org.apache.avro.data.RecordBuilder<GetRequest> {

    private java.lang.CharSequence client_id;
    private java.lang.CharSequence host;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(youling.studio.protocol.GetRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.client_id)) {
        this.client_id = data().deepCopy(fields()[0].schema(), other.client_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host)) {
        this.host = data().deepCopy(fields()[1].schema(), other.host);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing GetRequest instance
     * @param other The existing instance to copy.
     */
    private Builder(youling.studio.protocol.GetRequest other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.client_id)) {
        this.client_id = data().deepCopy(fields()[0].schema(), other.client_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.host)) {
        this.host = data().deepCopy(fields()[1].schema(), other.host);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'client_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getClientId() {
      return client_id;
    }

    /**
      * Sets the value of the 'client_id' field.
      * @param value The value of 'client_id'.
      * @return This builder.
      */
    public youling.studio.protocol.GetRequest.Builder setClientId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.client_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'client_id' field has been set.
      * @return True if the 'client_id' field has been set, false otherwise.
      */
    public boolean hasClientId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'client_id' field.
      * @return This builder.
      */
    public youling.studio.protocol.GetRequest.Builder clearClientId() {
      client_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'host' field.
      * @return The value.
      */
    public java.lang.CharSequence getHost() {
      return host;
    }

    /**
      * Sets the value of the 'host' field.
      * @param value The value of 'host'.
      * @return This builder.
      */
    public youling.studio.protocol.GetRequest.Builder setHost(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.host = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'host' field has been set.
      * @return True if the 'host' field has been set, false otherwise.
      */
    public boolean hasHost() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'host' field.
      * @return This builder.
      */
    public youling.studio.protocol.GetRequest.Builder clearHost() {
      host = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GetRequest build() {
      try {
        GetRequest record = new GetRequest();
        record.client_id = fieldSetFlags()[0] ? this.client_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.host = fieldSetFlags()[1] ? this.host : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GetRequest>
    WRITER$ = (org.apache.avro.io.DatumWriter<GetRequest>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GetRequest>
    READER$ = (org.apache.avro.io.DatumReader<GetRequest>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
