/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package youling.studio.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface MasterProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"MasterProtocol\",\"namespace\":\"youling.studio.protocol\",\"types\":[{\"type\":\"record\",\"name\":\"HeartBeatRequest\",\"fields\":[{\"name\":\"worder_id\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"port\",\"type\":\"int\"}]},{\"type\":\"record\",\"name\":\"HeartBeatResponse\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"msg\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"PutRequest\",\"fields\":[{\"name\":\"client_id\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"},{\"name\":\"uri\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"PutResponse\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"msg\",\"type\":\"string\"},{\"name\":\"blocks\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"map\",\"values\":\"string\"}}}]},{\"type\":\"record\",\"name\":\"GetRequest\",\"fields\":[{\"name\":\"client_id\",\"type\":\"string\"},{\"name\":\"host\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"GetResponse\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"msg\",\"type\":\"string\"}]}],\"messages\":{\"heartbeat\":{\"request\":[{\"name\":\"message\",\"type\":\"HeartBeatRequest\"}],\"response\":\"HeartBeatResponse\"},\"put\":{\"request\":[{\"name\":\"fileInfo\",\"type\":\"PutRequest\"}],\"response\":\"PutResponse\"},\"get\":{\"request\":[{\"name\":\"fileInfo\",\"type\":\"GetRequest\"}],\"response\":\"GetResponse\"}}}");
  /**
   */
  youling.studio.protocol.HeartBeatResponse heartbeat(youling.studio.protocol.HeartBeatRequest message) throws org.apache.avro.AvroRemoteException;
  /**
   */
  youling.studio.protocol.PutResponse put(youling.studio.protocol.PutRequest fileInfo) throws org.apache.avro.AvroRemoteException;
  /**
   */
  youling.studio.protocol.GetResponse get(youling.studio.protocol.GetRequest fileInfo) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends MasterProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = youling.studio.protocol.MasterProtocol.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void heartbeat(youling.studio.protocol.HeartBeatRequest message, org.apache.avro.ipc.Callback<youling.studio.protocol.HeartBeatResponse> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void put(youling.studio.protocol.PutRequest fileInfo, org.apache.avro.ipc.Callback<youling.studio.protocol.PutResponse> callback) throws java.io.IOException;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void get(youling.studio.protocol.GetRequest fileInfo, org.apache.avro.ipc.Callback<youling.studio.protocol.GetResponse> callback) throws java.io.IOException;
  }
}