/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package youling.studio.protocol;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface WorkerProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"WorkerProtocol\",\"namespace\":\"youling.studio.protocol\",\"types\":[{\"type\":\"record\",\"name\":\"ReadRequest\",\"fields\":[{\"name\":\"filename\",\"type\":\"string\"}]},{\"type\":\"record\",\"name\":\"ReadResponse\",\"fields\":[{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"msg\",\"type\":\"string\"}]}],\"messages\":{\"delete\":{\"request\":[{\"name\":\"request\",\"type\":\"ReadRequest\"}],\"response\":\"ReadResponse\"}}}");
  /**
   */
  youling.studio.protocol.ReadResponse delete(youling.studio.protocol.ReadRequest request) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends WorkerProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = youling.studio.protocol.WorkerProtocol.PROTOCOL;
    /**
     * @throws java.io.IOException The async call could not be completed.
     */
    void delete(youling.studio.protocol.ReadRequest request, org.apache.avro.ipc.Callback<youling.studio.protocol.ReadResponse> callback) throws java.io.IOException;
  }
}